### ISSUE TITLE
Unable to unzip example data on MacOS

### ISSUE THREAD

**Issue by gdj0nes** [metarank/ranklens#1]
I'm unable to decompress the data that is used for examples. I get the following error on MacOS for all of the .gz files

> gzip -d tmdb_movies.json.gz
> gzip: tmdb_movies.json.gz: not in gzip format

**Comment by vgoloviznin** [comment]
@gdj0nes to unzip gz files on macos use `gunzip` utility: 
```shell
gunzip tmdb_movies.json.gz
```

**Comment by gdj0nes** [comment]
> gunzip tmdb_movies.json.gz
> gunzip: tmdb_movies.json.gz: not in gzip format

**Comment by vgoloviznin** [comment]
Hm, rather weird as it's working like a charm for me. 

What MacOS version do you have? 

Can you also check that the file is fully downloaded (size: 891KB, sha1 checksum for the file: 22b04384decdd4e4233d498219652b9cf26beb27)

**Comment by gdj0nes** [comment]
Figured it out, it had to do with how I was pulling the data. Thanks for helping out!
